liip_imagine:
    
    filter_sets:
        cache: 

        my_thumb:

            quality: 75

            filters:
                thumbnail: { size: [120, 90], mode: outbound }

        avatar:

            quality: 75

            filters:
                thumbnail: { size: [40, 40], mode: outbound }

